from .authenticate_antisocial import AuthenticateAntisocialEndpoint
from .authenticate_social import AuthenticateSocialEndpoint
from .facebook import AuthorizeFacebookEndpoint
from .github import AuthorizeGithubEndpoint
from .google import AuthorizeGoogleEndpoint
from .logout import LogoutEndpoint
